Select * from DEPT_MANAGER
where DEPT_NO=102 OR DEPT_NO=103;
Select * from DEPT_MANAGER;
SELECT * from DEPARTMENT;
SELECT * from EMPLOYEE;

SELECT * from SALARY;
SELECT * from TITLES;

SELECT Emp.EMPLOYEE_NAME as DepManager 
from EMPLOYEE Emp
INNER JOIN DEPT_MANAGER DepMan
ON Emp.EMPLOYEE_ID = DepMan.EMPLOYEE_ID 
where (DepMan.DEPT_NO=102 OR DepMan.DEPT_NO=103) AND 
(DepMan.FROM_DATE > '2011-01-01'And DepMan.TO_DATE < '2017-04-01');

SELECT Emp.EMPLOYEE_NAME FemaleEmployee, SALARY.EMPLOYEE_SALARY as Salary
FROM EMPLOYEE Emp
INNER JOIN SALARY 
WHERE Emp.EMPLOYEE_GENDER = 'F' AND SALARY.EMPLOYEE_SALARY > 60000
order by Salary ASC ;

SELECT Emp.EMPLOYEE_NAME as Top5Employees
FROM EMPLOYEE Emp
Where Emp.EMPLOYEE_SALARY > 20000 AND Emp.EMPLOYEE_NAME LIKE'S%'
LIMIT 5;

SELECT Sum(SALARY.EMPLOYEE_SALARY) as TotalSalary
FROM SALARY 
WHERE SALARY.EMPLOYEE_NAME NOT LIKE'S%'AND SALARY.TO_DATE <'2017-01-01';

Select count(DepMan.EMPLOYEE_ID) TotalEmployee ,DepMan.DEPT_NO 
FROM DEPT_MANAGER DepMan
INNER JOIN DEPARTMENT Dep
ON Dep.depid = DepMan.DEPT_NO
GROUP by DepMan.DEPT_NO;

SELECT EMPLOYEE_ID, EMPLOYEE_NAME,EMPLOYEE_SALARY FROM EMPLOYEE;

SELECT DepMan.DEPT_NO as Departments, DepMan.EMPLOYEE_ID as EmployeeID, TITLES.EMPLOYEE_TITLE, EMPLOYEE.EMPLOYEE_NAME 
FROM DEPT_MANAGER DepMan 
INNER JOIN TITLES
ON DepMan.EMPLOYEE_ID = TITLES.EMPLOYEE_ID
INNER JOIN EMPLOYEE
ON TITLES.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID ;

Create Table TD_BANK(
CUSTOMER_ID INT(10),
CUSTOMER_NAME VARCHAR(25),
PHONE_NO INT(10),
BALANCE INT(25));
select * from TD_BANK_PRAKASH;
ALTER TABLE TD_BANK 
rename to TD_BANK_PRAKASH;

INSERT INTO TD_BANK_PRAKASH
VALUES (1,'PRAKASH',1237890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (2,'PRAKASH2',12367890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (3,'PRAKASH3',12567890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (4,'PRAKASH4',12367890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (5,'PRAKASH5',123467890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (6,'PRAKASH6',167890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (7,'PRAKASH7',123467890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (8,'PRAKASH8',1237890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (9,'PRAKASH9',00000000,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (10,'PRAKASH10',1237890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (11,'PRAKASH11',00000000,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (12,'PRAKASH',1237890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (13,'PRAKASH',1234567890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (14,'PRAKASH',00000000,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (15,'PRAKASH15',1234567890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (16,'PRAKASH16',1237890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (17,'PRAKASH17',00000000,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (18,'PRAKASH18',1234560,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (19,'PRAKASH19',67890,25);
INSERT INTO TD_BANK_PRAKASH
VALUES (20,'PRAKASH20',00000000,25);

TRUNCATE Table TD_BANK_PRAKASH;
SELECT DISTINCT (PHONE_NO), TD.CUSTOMER_ID, CUSTOMER_NAME, BALANCE FROM TD_BANK_PRAKASH TD;

Select * from DEPT_MANAGER;
SELECT * from DEPARTMENT;
SELECT * from EMPLOYEE;
SELECT * from SALARY;
SELECT * from TITLES;


SELECT Emp.EMPLOYEE_NAME as EmpName, Emp.EMPLOYEE_ADDRESS as EmpAdd, DepMan.DEPT_NO as DepNo, Emp.EMP_JOIN_DATE as JoinDate, DepMan.TO_DATE 
FROM DEPT_MANAGER DepMan
INNER JOIN EMPLOYEE Emp
ON DepMan.EMPLOYEE_ID = Emp.EMPLOYEE_ID
order by DepNo ASC;


SELECT Employee.EMPLOYEE_NAME , DepMan.DEPT_NO as Department, Employee.EMPLOYEE_SALARY 
FROM EMPLOYEE Employee , DEPT_MANAGER DepMan
Where DepMan.EMPLOYEE_ID = Employee.EMPLOYEE_ID  and EMPLOYEE_SALARY > 8000;

SELECT 
FROM 

SELECT Emp.EMPLOYEE_NAME 
FROM EMPLOYEE Emp, DEPT_MANAGER DepartmentMan
where (DepartmentMan.DEPT_NO = d005 OR DepartmentMan.DEPT_NO = d005) and Emp.EMPLOYEE_NAME LIKE'S'
LIMIT 5000;


SELECT Employee.EMPLOYEE_NAME 
FROM EMPLOYEE Employee
Where (Employee.EMPLOYEE_SALARY BETWEEN 25000 and 70000) AND (DateOfBirth BETWEEN 1960 and 1985);

SELECT Employee.EMPLOYEE_ID , Employee.EMPLOYEE_NAME , Employee.EMPLOYEE_SALARY , Department.depid ,Department.dname,Department.loc 
FROM DEPARTMENT Department 
INNER JOIN EMPLOYEE Employee 
ON Employee.DEPT_ID = Department.depid 
INNER JOIN TITLES
ON TITLES.EMPLOYEE_ID = Employee.EMPLOYEE_ID 
where TITLES.EMPLOYEE_TITLE = 'Developer' OR TITLES.EMPLOYEE_TITLE = 'Sr Developer'

SELECT SUM(Employee.EMPLOYEE_SALARY) as TotalSalary , COUNT(Titles.EMPLOYEE_TITLE) as TotalEmployees
FROM EMPLOYEE Employee
INNER JOIN TITLES Titles
ON Titles.EMPLOYEE_ID = Employee.EMPLOYEE_ID 
where Titles.EMPLOYEE_TITLE LIKE'Sr%';


SELECT SUM(Employee.EMPLOYEE_SALARY), Employee.EMPLOYEE_GENDER 
FROM EMPLOYEE Employee
Group BY Employee.EMPLOYEE_GENDER ;



Select Employee.EMPLOYEE_NAME , Count(Employee.EMPLOYEE_NAME)
FROM EMPLOYEE Employee
Group by Employee.EMPLOYEE_NAME 
HAVING COUNT(Employee.EMPLOYEE_NAME)>1; 


Select * from DEPT_MANAGER;
SELECT * from DEPARTMENT;
SELECT * from EMPLOYEE;
SELECT * from TITLES;

SELECT SUM(Employee.EMPLOYEE_SALARY) as Department_Total_Salary, Employee.DEPT_ID, Department.dname as DepartmentName
FROM DEPARTMENT Department
INNER JOIN EMPLOYEE Employee
ON Department.depid = Employee.DEPT_ID
INNER JOIN TITLES Titles 
ON Employee.EMPLOYEE_ID = Titles.EMPLOYEE_ID 
WHERE Titles.EMPLOYEE_TITLE = 'Assisstant Engineer'
GROUP by Employee.DEPT_ID;

SELECT Employee.EMPLOYEE_ID , Titles.EMPLOYEE_TITLE 
From EMPLOYEE Employee, TITLES Titles
Where (Employee.EMPLOYEE_ID = Titles.EMPLOYEE_ID ) 
AND (Titles.EMPLOYEE_TITLE = 'Develper' OR Titles.EMPLOYEE_TITLE = 'Team Lead');



SELECT SUM(EMPLOYEE.EMPLOYEE_SALARY), EMPLOYEE.EMPLOYEE_ADDRESS FROM EMPLOYEE GROUP BY EMPLOYEE.EMPLOYEE_ADDRESS ;